### ISSUE TITLE
AttributeError: 'Command' object has no attribute 'option_list'

### ISSUE THREAD

**Issue by asa511** [tomturner/django-tenants#107]
I am using release 1.1.9 with Django 1.10.2.

When I run the management command create_tenant_superuser, I get the following error:

AttributeError: 'Command' object has no attribute 'option_list'

The stack trace is as follows:

```
Traceback (most recent call last):
  File ".\manage.py", line 22, in <module> execute_from_command_line(sys.argv)
  File "~\.virtualenvs\test\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line utility.execute()
  File "~\.virtualenvs\test\lib\site-packages\django\core\management\__init__.py", line 359, in execute self.fetch_command(subcommand).run_from_argv(self.argv)
  File "~\.virtualenvs\test\lib\site-packages\django\core\management\__init__.py", line 208, in fetch_command klass = load_command_class(app_name, subcommand)
  File "~\.virtualenvs\test\lib\site-packages\django\core\management\__init__.py", line 41, in load_command_class     return module.Command()
  File "~\.virtualenvs\test\lib\site-packages\django_tenants\management\commands\__init__.py", line 116,
    in __new__
    obj.option_list = obj.command_instance.option_list
AttributeError: 'Command' object has no attribute 'option_list'
```

**Comment by tomturner** [comment]
I get the same error I will fix it shortly
