### ISSUE TITLE
AttributeError: 'MyTenantTestCase' object has no attribute 'atomics'

### ISSUE THREAD

**Issue by BillBrower** [tomturner/django-tenants#159]
I'm getting this error when I use `django_tenants.test.cases.TenantTestCase`.

```
Traceback (most recent call last):
  File "/my_api/lib/python3.4/site-packages/django/test/testcases.py", line 216, in __call__
    self._post_teardown()
  File "/my_api/lib/python3.4/site-packages/django/test/testcases.py", line 925, in _post_teardown
    self._fixture_teardown()
  File "/my_api/lib/python3.4/site-packages/django/test/testcases.py", line 1083, in _fixture_teardown
    self._rollback_atomics(self.atomics)
AttributeError: 'MyTenantTestCase' object has no attribute 'atomics'
```

It seems pretty straight forward. `django_tenants.test.cases.TenantTestCase` doesn't call `super().setUpClass()` in its `setUpClass` method:

```python
@classmethod
def setUpClass(cls):
    cls.sync_shared()
    cls.add_allowed_test_domain()
    cls.tenant = get_tenant_model()(schema_name=cls.get_test_schema_name())
    cls.setup_tenant(cls.tenant)
    cls.tenant.save(verbosity=cls.get_verbosity())

    # Set up domain
    tenant_domain = cls.get_test_tenant_domain()
    cls.domain = get_tenant_domain_model()(tenant=cls.tenant, domain=tenant_domain)
    cls.setup_domain(cls.domain)
    cls.domain.save()

    connection.set_tenant(cls.tenant)
```

So `django.test.testcases.TestCase.setUpClass` never gets called and `cls.cls_atomics = cls._enter_atomics()` never gets set.

I am subclassing `django_tenants.test.cases.TenantTestCase` so that I can make the client compatible with Django Rest Framework:

```python
from django.core import mail
from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient
from rest_framework.test import ForceAuthClientHandler


class MultiTenantAPIClient(TenantClient):
    """
    This is a combination of the django-tenants TenantClient and
    DRFs APIClient.
    """
    def __init__(self, tenant, enforce_csrf_checks=False, **defaults):
        super(MultiTenantAPIClient, self).__init__(tenant, **defaults)
        self.handler = ForceAuthClientHandler(enforce_csrf_checks)
        self._credentials = {}

    def credentials(self, **kwargs):
        """
        Sets headers that will be used on every outgoing request.
        """
        self._credentials = kwargs

    def force_authenticate(self, user=None, token=None):
        """
        Forcibly authenticates outgoing requests with the given
        user and/or token.
        """
        self.handler._force_user = user
        self.handler._force_token = token
        if user is None:
            self.logout() # Also clear any possible session info if required

    def logout(self):
        self._credentials = {}

        # Also clear any `force_authenticate`
        self.handler._force_user = None
        self.handler._force_token = None

        if self.session:
            super(MultiTenantAPIClient, self).logout()


class MultiTenantAPITestCase(TenantTestCase):
    client_class = MultiTenantAPIClient

    def _pre_setup(self):
        """
        Perform pre-test setup:
        * Create a test client.
        * Clear the mail test outbox.
        """
        self.client = self.client_class(tenant=self.tenant)
        mail.outbox = []
```

I also get the same error if I subclass `FastTenantTestCase` instead of `TenantTestCase` though and overriding the `setUpClass` method so that `cls.cls_atomics = cls._enter_atomics()` is called doesn't help either:

```python
@classmethod
def setUpClass(cls):
    super().setUpClass()
    cls.cls_atomics = cls._enter_atomics()
```
For reference I'm using Django 1.11 and release 1.3.4 of django-tenants. That said, there haven't been any updates to `django_tenants.test.cases` since 1.3.4 was released so if it's a versioning issue at all I think the problem would probably lie with Django. Has anyone run into this before?

**Comment by tomturner** [comment]
I will have a look

**Comment by BillBrower** [comment]
Thank you, here is the entirety of my subclassed version of `django_tenants.test.cases.TenantTestCase` if it helps.

```python
from django.conf import settings
from django.core import mail
from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient
from rest_framework.test import ForceAuthClientHandler


class MultiTenantAPIClient(TenantClient):
    """
    This is a combination of the django-tenants TenantClient and
    DRFs APIClient.
    """
    def __init__(self, tenant, enforce_csrf_checks=False, **defaults):
        super(MultiTenantAPIClient, self).__init__(tenant, **defaults)
        self.handler = ForceAuthClientHandler(enforce_csrf_checks)
        self._credentials = {}

    def credentials(self, **kwargs):
        """
        Sets headers that will be used on every outgoing request.
        """
        self._credentials = kwargs

    def force_authenticate(self, user=None, token=None):
        """
        Forcibly authenticates outgoing requests with the given
        user and/or token.
        """
        self.handler._force_user = user
        self.handler._force_token = token
        if user is None:
            self.logout() # Also clear any possible session info if required

    def logout(self):
        self._credentials = {}

        # Also clear any `force_authenticate`
        self.handler._force_user = None
        self.handler._force_token = None

        if self.session:
            super(MultiTenantAPIClient, self).logout()


class MultiTenantAPITestCase(TenantTestCase):
    client_class = MultiTenantAPIClient

    def _pre_setup(self):
        """
        Perform pre-test setup:
        * Create a test client.
        * Clear the mail test outbox.
        """
        self.client = self.client_class(tenant=self.tenant)
        mail.outbox = []
```

**Comment by BillBrower** [comment]
So I was wrong about this issue being related to `tearDownClass`. I looked at the Django source code again `_post_teardown()` always gets called:

`TestCase` is a sublcass of`TransactionTestCase` which is a subclass of `SimpleTestCase` and `_post_teardown()` always gets called as part of `SimpleTestCase`'s `__call__` method.

```python
class SimpleTestCase(unittest.TestCase):

    def __call__(self, result=None):
        """
        Wrapper around default __call__ method to perform common Django test
        set up. This means that user-defined Test Cases aren't required to
        include a call to super().setUp().
        """
        testMethod = getattr(self, self._testMethodName)
        skipped = (
            getattr(self.__class__, "__unittest_skip__", False) or
            getattr(testMethod, "__unittest_skip__", False)
        )

        if not skipped:
            try:
                self._pre_setup()
            except Exception:
                result.addError(self, sys.exc_info())
                return
        super(SimpleTestCase, self).__call__(result)
        if not skipped:
            try:
                self._post_teardown()
            except Exception:
                result.addError(self, sys.exc_info())
                return
```

**Comment by BillBrower** [comment]
I figured it out. My code should be

```python
class MultiTenantAPITestCase(TenantTestCase):
    def _pre_setup(self):
        """
        Perform pre-test setup:
        * Create a test client.
        * Clear the mail test outbox.
        """
        super()._pre_setup()
        self.client_class = MultiTenantAPIClient
        self.client = self.client_class(tenant=self.tenant)
```

I had originally copied the `_pre_setup()` method from `SimpleTestCase`, meaning to take it from `TestCase`, because if you call `super()._pre_setup()` with `client_class` set to `TenantClient`, or my subclassed version of it, you'll get this error:

```
Traceback (most recent call last):
  File "/my_api/lib/python3.4/site-packages/django/test/testcases.py", line 209, in __call__
    self._pre_setup()
  File "/my_api/api/tenants/test_utils.py", line 87, in _pre_setup
    super()._pre_setup()
  File "/my_api/lib/python3.4/site-packages/django/test/testcases.py", line 844, in _pre_setup
    super(TransactionTestCase, self)._pre_setup()
  File "/my_api/lib/python3.4/site-packages/django/test/testcases.py", line 227, in _pre_setup
    self.client = self.client_class()
TypeError: __init__() missing 1 required positional argument: 'tenant'
```

That said, the version of `_pre_setup()` from `SimpleTestCase` never calls `self._fixture_setup()` so `self.atomics` never gets set. So the solution is to leave `client_class` undefined in your class definition and set it dynamically after you've called `super()._pre_setup()`.
