### ISSUE TITLE
PostGis and Tenants

### ISSUE THREAD

**Issue by coler-j** [tomturner/django-tenants#209]
For PostGis support the docs say to add `ORIGINAL_BACKEND = "django.contrib.gis.db.backends.postgis"`. I have this, however, when I go to create a new tenant I get the following error: 

```
Traceback (most recent call last):
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\celery\app\trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\celery\app\trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "C:\Users\Cole\Documents\GitHub\Elevate-RA-Django-App\returns_app\apps\tenant_stores\tasks.py", line 28, in create_tenant_task
    tenant.save()
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django_tenants\models.py", line 93, in save
    self.create_schema(check_if_exists=True, verbosity=verbosity)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django_tenants\models.py", line 143, in create_schema
    verbosity=verbosity)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\core\management\__init__.py", line 141, in call_command
    return command.execute(*args, **defaults)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django_tenants\management\commands\migrate_schemas.py", line 63, in handle
    executor.run_migrations(tenants=tenants)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django_tenants\migration_executors\standard.py", line 15, in run_migrations
    run_migrations(self.args, self.options, self.codename, schema_name, idx=idx, count=len(tenants))
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django_tenants\migration_executors\base.py", line 34, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\core\management\commands\migrate.py", line 77, in handle
    connection.prepare_database()
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\contrib\gis\db\backends\postgis\base.py", line 26, in prepare_database
    cursor.execute("CREATE EXTENSION IF NOT EXISTS postgis")
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\users\cole\appdata\local\programs\python\python36-32\lib\site-packages\django\db\backends\utils.py", line 83, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "spatial_ref_sys" does not exist
```

The `spatial_ref_sys` table exists within my public schema. The `django.contrib.gis` app is in my shared  apps.

Any ideas?

**Comment by coler-j** [comment]
(Furthermore the postgis extension EXISTS for the public schema)

**Comment by coler-j** [comment]
(Created an SO too: https://stackoverflow.com/questions/53544168/posgis-and-django-tenants)

**Comment by coler-j** [comment]
**Final solution here:**

The issue seems to be cause by the default PostGis backend, specifically the call to prepare the database for migration, by explicitly setting the search path prior to calling `CREATE EXTENSION IF NOT EXISTS postgis` I was able to migrate/create a schema by creating a custom DB backend that overrides this behaviour:

```
from django.contrib.gis.db.backends.postgis.base import (
    DatabaseWrapper as OriginalPostGisDatabaseWrapper,
)
from django_tenants.utils import get_public_schema_name


class DatabaseWrapper(OriginalPostGisDatabaseWrapper):
    """
    This database wrapper explicitly sets the search path when preparing the database, as
    multi-schema environments (like with Django-tenants) can cause issues with the PostGis
    backend.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.PUBLIC_SCHEMA_NAME = get_public_schema_name()

    def prepare_database(self):
        # Check that postgis extension is installed.
        with self.cursor() as cursor:
            cursor.execute('SET search_path = %s', params=[self.PUBLIC_SCHEMA_NAME])
            cursor.execute("CREATE EXTENSION IF NOT EXISTS postgis")'
```

Then, set your `ORIGINAL_BACKEND` setting to the location of the above DB backend instead of the standard PostGis backend.

**Comment by kosz85** [comment]
It's not broken in django-tenants :) It's rather caused by your ability to configure it. You have to remeber about schemas, and the fact that other libs aren't aware of it. I was using postgis, and really there were no problem, just you need to share extension between schemas properly. You doing `CREATE EXSTENSION IF NOT EXISTS ...` did it by brute force. I would suggest to make it properly, as now on opening each cursor you have additional query with check added, so it may slow down things at production environment.
I suggest to add it in schema migration.

**Comment by coler-j** [comment]
Actually, that create extension command is part of the base postgis DB
backend. Have you used postgis recently? As thete have been changes which
disallow you from moving the schema of the post gis extension tables. So it
is currently broken, but the above fixes it.

**Comment by coler-j** [comment]
(All i changed was explicitly setting to schema) for the prepare db
command. This is only run during migrations and not with each connection.

**Comment by coler-j** [comment]
I think of you were to install Django 2.0.9 + post gis you would run into
these problems as well.

Although i dont think there are tests to cover this right now.
