### ISSUE TITLE
Adding and removing a model from a tenant_app breaks the migrate_schemas

### ISSUE THREAD

**Issue by george-silva** [tomturner/django-tenants#23]
Hello guys,

Just testing here:

1. I had a simple model definition on a tenant schema. It ran just fine.
2. I added a new model and ran migrate_schemas (without --shared);
3. Removed that model;
4. Ran migrate_schemas again;
5. Break;

```python
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django_tenants/management/commands/migrate_schemas.py", line 46, in handle
    self.run_migrations(self.schema_name, settings.SHARED_APPS, options)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django_tenants/management/commands/migrate_schemas.py", line 64, in run_migrations
    command.execute(*self.args, **options)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 225, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py", line 81, in update_contenttypes
    ct.delete()
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/models/base.py", line 871, in delete
    collector.collect([self])
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 228, in collect
    elif sub_objs:
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/george/projetos/.virtualenvs/greentape/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_permission" does not exist
LINE 1: ...ntent_type_id", "auth_permission"."codename" FROM "auth_perm...
```

**Comment by kosz85** [comment]
You have to post more info:
1. This model was shared or not?
2. New model was shared or not?
3. As I assume this new added model, and you did makemigrations again?
4. with or without `--shared`?
5. Traceback looks like you don't have public schema in your `search_path` or you dropped `auth_permissions` (I assume that standard django`auth` app is set as shared app)

**Comment by george-silva** [comment]
I've done some testing here, and it works just fine.

The docs somewhat imply that you don't need to run ```makemigrations```. The test I did above was without using any migrations.

Sorry for the noise - but I assumed that this was not necessary, since the documentation does mention ```makemigrations``` - at all. Stupid of my part, but I'll open up a ticket a file a patch with a few extra lines on the documentation;
