### ISSUE TITLE
Error relating to no module for "tenant_only" 

### ISSUE THREAD

**Issue by locheachles** [tomturner/django-tenants#236]
Hello all, thanks for any help.  I successfully completed the tutorial/demo project and have built a "django-tenants" project now from scratch.  However, when I get to the step for "migrate_schemas --shared" to prep the DB I get the following error:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/michaelcareyST/Desktop/BevSoft/bevsoft-project/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/michaelcareyST/Desktop/BevSoft/bevsoft-project/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/michaelcareyST/Desktop/BevSoft/bevsoft-project/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/michaelcareyST/Desktop/BevSoft/bevsoft-project/venv/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/michaelcareyST/Desktop/BevSoft/bevsoft-project/venv/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tenant_only'

This is my first multi-tenant Django adventure so forgive me if this is something quite obvious... I couldn't find this in the docs (though I see a "tenant-only" app in the demo) and any help would be appreciated.

**Comment by tomturner** [comment]
Please post you settings file

**Comment by locheachles** [comment]
Hey Tom -  I figured it out. Thank you - should've come back to close this.
