### ISSUE TITLE
InconsistentMigrationHistory when running many test suites against database

### ISSUE THREAD

**Issue by thenewguy** [tomturner/django-tenants#429]
I am working on an integration and attempting to run each test suite and an integration test suite with tox.

Note that each test suite passes just fine when run against a fresh database.  However, I am getting `django.db.migrations.exceptions.InconsistentMigrationHistory` when running them back to back via a loop using subprocess.Popen against the same infrastructure.

I was following a traceback and noticed the migrations do not specify the test database here: https://github.com/tomturner/django-tenants/blob/master/django_tenants/test/cases.py#L76

Should they be?  This error message indicates the test is running migrations on the 'default' database instead of the test database: `django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.`

Is this intended?  Do I need to drop the database between test suites?  Each test suite runs as its own django project (like `DJANGO_SETTINGS_MODULE=foo.settings; python manage.py test`) against the same docker containers for infrastructure (db, cache, etc)

Traceback:
```
 Traceback (most recent call last):
   File "/var/lib/project/bin/runtests_integration", line 38, in <module>
     runtests()
   File "/var/lib/project/bin/runtests_integration", line 34, in runtests
     execute_from_command_line(argv)
   File "/var/lib/project/django/core/management/__init__.py", line 401, in execute_from_command_line
     utility.execute()
   File "/var/lib/project/django/core/management/__init__.py", line 395, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/var/lib/project/django/core/management/commands/test.py", line 23, in run_from_argv
     super().run_from_argv(argv)
   File "/var/lib/project/django/core/management/base.py", line 328, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/var/lib/project/django/core/management/base.py", line 369, in execute
     output = self.handle(*args, **options)
   File "/var/lib/project/django/core/management/commands/test.py", line 53, in handle
     failures = test_runner.run_tests(test_labels)
   File "/var/lib/project/django/test/runner.py", line 684, in run_tests
     old_config = self.setup_databases(aliases=databases)
   File "/var/lib/project/django/test/runner.py", line 606, in setup_databases
     self.parallel, **kwargs
   File "/var/lib/project/django/test/utils.py", line 173, in setup_databases
     serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
   File "/var/lib/project/django/db/backends/base/creation.py", line 72, in create_test_db
     run_syncdb=True,
   File "/var/lib/project/django/core/management/__init__.py", line 168, in call_command
     return command.execute(*args, **defaults)
   File "/var/lib/project/django/core/management/base.py", line 369, in execute
     output = self.handle(*args, **options)
   File "/var/lib/project/django_tenants/management/commands/migrate_schemas.py", line 49, in handle
     executor.run_migrations(tenants=[self.PUBLIC_SCHEMA_NAME])
   File "/var/lib/project/django_tenants/migration_executors/standard.py", line 11, in run_migrations
     run_migrations(self.args, self.options, self.codename, self.PUBLIC_SCHEMA_NAME)
   File "/var/lib/project/django_tenants/migration_executors/base.py", line 36, in run_migrations
     MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
   File "/var/lib/project/django/core/management/base.py", line 369, in execute
     output = self.handle(*args, **options)
   File "/var/lib/project/django/core/management/base.py", line 83, in wrapped
     res = handle_func(*args, **kwargs)
   File "/var/lib/project/django/core/management/commands/migrate.py", line 89, in handle
     executor.loader.check_consistent_history(connection)
   File "/var/lib/project/django/db/migrations/loader.py", line 299, in check_consistent_history
     connection.alias,
 django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.
```

**Comment by thenewguy** [comment]
I am going to close this. I didn't notice the issue is against the pooler not the database
