### ISSUE TITLE
django-rest-framework + django-tenants = 'put' bug?

### ISSUE THREAD

**Issue by bartmika** [tomturner/django-tenants#82]
Hello,

I've been trying to figure this bug I encountered. I've been at this for over two days now and I am still scratching my head here. I am wondering if I've encountered a bug with django-tenants? More specifically, I suspect there is something wrong with the **put** function that I inherit from **TenantTestCase**. 

So basically I have this unit test file which runs & works successfully except the **test_put_with_authorization** unit test. 

The console log I get is:

```python
Creating test database for alias 'default'...
.......F
======================================================================
FAIL: test_put_with_authorization (api.tests.foundation.test_brand.APIBrandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/bartlomiejmika/Developer/rodolfomartinez/smegurus/py-bizmula/api/tests/foundation/test_brand.py", line 146, in test_put_with_authorization
    self.assertEqual(response.status_code, status.HTTP_200_OK)
AssertionError: 415 != 200
```

And now I attach my files.

**tests.py**

```python
import json
from django.db import transaction
from django.core.urlresolvers import resolve, reverse
from django.http import HttpRequest
from django.http import QueryDict
from django.test import TestCase
from django.test import Client
from django.utils import translation
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from rest_framework import status
from rest_framework.test import APIClient
from rest_framework.test import APITestCase
from api.views import authentication
from api.models.foundation.brand import Brand


from django.core.urlresolvers import resolve, reverse
from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient


TEST_USER_EMAIL = "ledo@gah.com"
TEST_USER_USERNAME = "ledo"
TEST_USER_PASSWORD = "GalacticAllianceOfHumankind"


class APIBrandTest(APITestCase, TenantTestCase):
    fixtures = []

    @classmethod
    def setUpTestData(cls):
        # Initialize our test user.
        user = User.objects.create_user(  # Create our user.
            email=TEST_USER_EMAIL,
            username=TEST_USER_USERNAME,
            password=TEST_USER_PASSWORD
        )
        user.is_active = True
        user.save()

    @transaction.atomic
    def setUp(self):
        translation.activate('en')  # Set English.
        super(APIBrandTest, self).setUp()

        # Initialize our test data.
        self.user = User.objects.get()
        token = Token.objects.get(user__username=TEST_USER_USERNAME)

        # Setup.
        self.unauthorized_client = TenantClient(self.tenant)
        self.authorized_client = TenantClient(self.tenant, HTTP_AUTHORIZATION='Token ' + token.key)

        Brand.objects.create(owner=self.user)
        Brand.objects.create(owner=self.user)
        Brand.objects.create(owner=self.user)

        # Above taken from:
        # http://www.django-rest-framework.org/api-guide/testing/#authenticating

    @transaction.atomic
    def tearDown(self):
        brands = Brand.objects.all()
        for brand in brands.all():
            brand.delete()

    @transaction.atomic
    def test_list(self):
        response = self.unauthorized_client.get('/api/brand/')
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    @transaction.atomic
    def test_list_with_authentication(self):
        response = self.authorized_client.get('/api/brand/')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    @transaction.atomic
    def test_post(self):
        data = {
            'name': 'Unit Test',
            'description': 'Used for unit testing purposes.',
            'owner': self.user.id
        }
        response = self.unauthorized_client.post('/api/brand/')
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    @transaction.atomic
    def test_post_with_authentication(self):
        data = {
            'name': 'Unit Test',
            'description': 'Used for unit testing purposes.',
            'owner': self.user.id
        }
        response = self.authorized_client.post('/api/brand/', data, format="json")
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)

    @transaction.atomic
    def test_put(self):
        # Delete any previous data.
        postal_addesses = Brand.objects.all()
        for postal_address in postal_addesses.all():
            postal_addesses.delete()

        # Create a new object with our specific test data.
        Brand.objects.create(
            id=1,
            name="Unit Test",
            description="Used for unit testing purposes."
        )

        # Run the test.
        data = {
            'id': 1,
            'name': 'Unit Test',
            'description': 'Used for unit testing purposes.',
            'owner': self.user.id
        }
        response = self.unauthorized_client.put('/api/brand/1/', data, format="json")
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

#TODO: INVESTIGATE AND FIX THIS BUG.
    @transaction.atomic
    def test_put_with_authorization(self):
        # Delete any previous data.
        brands = Brand.objects.all()
        for brand in brands.all():
            brand.delete()

        # Create a new object with our specific test data.
        Brand.objects.create(
            id=1,
            name="Unit Test",
            description="Used for unit testing purposes.",
            owner_id=self.user.id
        )

        # Run the test.
        data = {
            'id': 1,
            'name': 'Unit Test',
            'description': 'Used for unit testing purposes.',
            'owner': self.user.id
        }
        response = self.authorized_client.put('/api/brand/1/', data, format="json",)
        self.assertEqual(response.status_code, status.HTTP_200_OK) # <=------ returns 415 status????

    @transaction.atomic
    def test_delete(self):
        response = self.unauthorized_client.delete('/api/brand/1/')
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    @transaction.atomic
    def test_delete_with_authentication(self):
        response = self.authorized_client.delete('/api/brand/1/')
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)

```

**serializer.py**

```python
from django.contrib.auth.models import User, Group
from rest_framework import serializers
from api.models.foundation.brand import Brand

class BrandSerializer(serializers.ModelSerializer):
    class Meta:
        model = Brand
        fields = ('id', 'created', 'last_modified', 'owner', 'name', 'alternate_name', 'description', 'url')
```

**view.py**

```python
import django_filters
from django.contrib.auth.models import User
from rest_framework import viewsets
from rest_framework import filters
from rest_framework import permissions
from rest_framework import authentication
from api.pagination import LargeResultsSetPagination
from api.permissions import IsOwnerOrReadOnly, BannedPermission
from api.serializers.foundation  import BrandSerializer
from api.models.foundation.brand import Brand


class BrandFilter(django_filters.FilterSet):
    class Meta:
        model = Brand
        fields = ['created', 'last_modified', 'owner', 'name', 'alternate_name', 'description', 'url']


class BrandViewSet(viewsets.ModelViewSet):
    queryset = Brand.objects.all()
    serializer_class = BrandSerializer
    pagination_class = LargeResultsSetPagination
    authentication_classes = (authentication.TokenAuthentication,)
    permission_classes = (permissions.IsAuthenticated, IsOwnerOrReadOnly, BannedPermission)
    filter_class = BrandFilter
```

**Comment by tomturner** [comment]
Sorry I don't know the answer as i don't use django-rest-framework

**Comment by kosz85** [comment]
@bartmika  you should use sometimes tools you have:
http://stackoverflow.com/questions/15153048/django-rest-framework-http-put-failing-with-415-on-django-1-5

It's not related to django-tenants at all.

**Comment by bartmika** [comment]
Thank you @kosz85, your linked help fix the problem!
