### ISSUE TITLE
Unit Testing = Can't create tenant outside the public schema. Current schema is test.

### ISSUE THREAD

**Issue by bartmika** [tomturner/django-tenants#86]
Hello,

I am attempting to write a unit test which involves creating a tenant. However, it errors with the following:

```python
Creating Tenant
Can't create tenant outside the public schema. Current schema is test.
```

My **tests.py** contents look like this:

```python
import json
from django.core.urlresolvers import resolve, reverse
from django.db import transaction
from django.test import TestCase
from django.utils import translation
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from rest_framework import status
from rest_framework.test import APIClient
from rest_framework.test import APITestCase
from rest_framework.authtoken.models import Token
from api.views import authentication


from django.core.urlresolvers import resolve, reverse
from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient


TEST_USER_EMAIL = "zzz@xxx.com"
TEST_USER_USERNAME = "yyy"
TEST_USER_PASSWORD = "xxx"


class APIClientTestCase(APITestCase, TenantTestCase):
    fixtures = [
        # 'banned_domains.json',
        # 'banned_ips.json',
        # 'banned_words.json',
        # 'groups',
        # 'permissions',
    ]

    @classmethod
    def setUpTestData(cls):
        user = User.objects.create_user(  # Create our User.
            email=TEST_USER_EMAIL,
            username=TEST_USER_USERNAME,
            password=TEST_USER_PASSWORD
        )
        user.is_active = True
        user.save()
        Token.objects.create(user_id=user.id)  # Create our User's Token.

    @transaction.atomic
    def setUp(self):
        translation.activate('en')  # Set English.
        super(APIClientTestCase, self).setUp()

        self.user = User.objects.get()
        token = Token.objects.get(user__username=TEST_USER_USERNAME)
        self.unauthorized_client = TenantClient(self.tenant)
        self.authorized_client = TenantClient(self.tenant, HTTP_AUTHORIZATION='Token ' + token.key, format='json',)

    @transaction.atomic
    def tearDown(self):
        users = User.objects.all()
        for user in users.all():
            user.delete()
        tokens = Token.objects.all()
        for token in tokens.all():
            token.delete()

    @transaction.atomic
    def test_create_tenant(self):
        from base.models import Client

        # First tenant.
        tenant = Client(
            schema_name='demo',
            name='Den Demo',
            paid_until='2016-12-05',
            on_trial=True
        )
        try:
            print("Creating Tenant")
            tenant.save() # migrate_schemas automatically called, your tenant is ready to be used!
        except Exception as e:
            print(e)
```

Do you guys have any ideas how I can create a unit test where I can create a tenant?

Thanks!

**Comment by bartmika** [comment]
Addendum. Also I attempted to run the command from console and I get the same error:

```python
    @transaction.atomic
    def test_api_create_tenant_with_success(self):
        from django.core.management import call_command
        call_command('create_tenant', '--domain_url=newtenant.net --schema_name=new_tenant --name=new_tenant', verbosity=0, interactive=False)
```

I get this error:

```python
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/api/tests/test_client.py", line 68, in test_api_create_tenant_with_success
    call_command('create_tenant', '--domain_url=newtenant.net --schema_name=new_tenant --name=new_tenant', verbosity=0, interactive=False)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/env/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/env/lib/python3.4/site-packages/django_tenants/management/commands/create_tenant.py", line 58, in handle
    tenant = self.store_tenant(**tenant_data)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/env/lib/python3.4/site-packages/django_tenants/management/commands/create_tenant.py", line 85, in store_tenant
    tenant = get_tenant_model().objects.create(**fields)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/env/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/env/lib/python3.4/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/anotherguy/Developer/someguy/py-the-new-project/env/lib/python3.4/site-packages/django_tenants/models.py", line 76, in save
    "Current schema is %s." % connection.schema_name)
Exception: Can't create tenant outside the public schema. Current schema is test.
```

**Comment by kosz85** [comment]
You have you answer at `Exception` message, you are on schema **test**, you need to switch tenant to **public** schema. Change it using db connection, or  by `Tenant(schema_name='public').activate()` or by `Tenant.objects.get(schema_name='public').activate()` or whatever, there is plenty of ways to switch tenant to public schema ;)
I like using descriptors and `with:` smth like:
```
with Tenant(schema_name='public'):
    # Create tenant in this block
# Here would be restored old tenant
```
then you don't need to restore previous tenant, as it would be restored automatically.

In first post, you used `TenantTestCase` which sets schema to `test` schema, and in second post looking at traceback it's the same problem. So **this issue should be closed**, as there is no real issue. I'm creating and deleting many tenants each day like this ;)
Please read Exceptions next time.

**Comment by bartmika** [comment]
Thank you very much @kosz85. This completely fixed my issue! I do have to admit, there is an opportunity to improve the documentations so future developers won't make my mistake. I think something like this appended to the **Tests** section would do the trick:

(In: https://django-tenants.readthedocs.io/en/latest/test.html )
# Tests 
## Running the tests
...

## Updating your app’s tests to work with django_tenants

...

## Additional information

...

## Unit Testing with Different Schemas (NEW SECTION)
Unit testing with different schemas is possible and works as follows. Let's assume your ``TenantMixen`` model looks as follows:

**models.py** 
```python
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django_tenants.models import TenantMixin, DomainMixin


class Organization(TenantMixin):
    # General Information.
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User,
        help_text=_('The user whom owns this thing.'),
        blank=True,
        null=True
    )
    name = models.CharField(
        _("Name"),
        max_length=255,
        help_text=_('The name of the item.'),
        blank=True,
        null=True,
    )

    # Payment Information.
    on_trial = models.BooleanField(default=False)
    paid_until =  models.DateField(
        auto_now_add=True,
        blank=True,
        null=True,
    )

    # Django-Tenant Information.
    auto_create_schema = True
    auto_drop_schema = True


class Domain(DomainMixin):
    pass
```

Now to unit test using different **schema names**, follow this example:
**tests.py**
```python
from django.db import transaction
from django.utils import translation
from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient
from models import Organization   # Our test model which inherits TenantMixin


class MultiSchemaOrganizationTestCases(TenantTestCase):
    fixtures = []  # Place any fixtures you would like.

    @classmethod
    def setUpTestData(cls):
       pass  # Place any setup test data if you would like.

    def setup_tenant(self, tenant):
        """
        Add any additional setting to the tenant before it get saved. This is required if you have
        required fields.
        """
        tenant.name = "Test Company"

    @transaction.atomic
    def setUp(self):
        translation.activate('en')  # Set English
        super(MultiSchemaOrganizationTestCases, self).setUp()
        self.c = TenantClient(self.tenant)

    @transaction.atomic
    def tearDown(self):
        pass 

    @transaction.atomic
    def test_as_public_schema_view(self):
        with PublicOrganization(schema_name='public'):
           # Create tenant in this block
            org = PublicOrganization.objects.create(schema_name='public')
            self.tenant = org

            # Write your tests here.
            print(self.tenant.schema_name) # Output will be 'public'

        # Here would be restored old tenant

    @transaction.atomic
    def test_as_tenant_schema_view(self):
        # Write your tests here.
        print(self.tenant.schema_name) # Output will be 'test'
```


What do you guys think?

**Comment by kosz85** [comment]
You did smth really wierd :)

To test not as **tenant** just don't use `TenantTestCase` as base for your test class.

The `test_as_public_schema_view` is awful, you can do it just as:
```
    @transaction.atomic
    def test_as_public_schema_view(self):
        with Organization(schema_name='public') as org:
           # Create tenant in this block
            # Not needed
            #org = PublicOrganization.objects.create(schema_name='public')
            #self.tenant = public

            # Write your tests here.
            print(org.schema_name) # Output will be 'public'

        # Here would be restored old tenant
```

In fact you can just create decorator to switch schema, `with:` is just code block decorator. You can create `TenantAndPublicTestCase`  with setup and teardown for tenant **test** and create decorator `use_schema(name)` then just use as `use_schema('public')` or `use_schema('test')`.

I don't really understand why you are trying this `PublicOrganization.objects.create(schema_name='public')` when you are running test, your DB is already migrated, so public schema is already there, more correct would be use `get(schema_name='public')`  as I suggested.
You always have just one **public** schema. If you need more then switch schema (so you need your data from DB) do just smth like:

```
with Organization.objects.get(schema_name='public') as public:
    # your block of code
```

**Comment by bartmika** [comment]
Thanks again for your explanation. I see what you mean.

May I kindly request we get documentation on this issue? I would greatly appreciate it!

**Comment by kosz85** [comment]
Please tell what you exactly miss here, maybe I would have couple of minutes to do it.

**Comment by bartmika** [comment]
Lets pretend you have a simple app with two URLs. One URL you are ONLY allowed to be accessed from a **public** schema and the other URL can ONLY be accessed by **tenants** schema. I would like to see help documents how to set up unit testing for those two schemas (public and tenant) and see how it affects this simple app.

**Comment by rodolfomartinez** [comment]
It would be really helpful it there were an example of running unit tests with ‘public’ and ‘tenant’ schemas

**Comment by bartmika** [comment]
I figured it! No need to write anything up @kosz85. I'll add to this ticket later an explanation of how to do it. (Or perhaps open up a new Ticket for updating the documentation)

**Comment by BillBrower** [comment]
@bartmika Did you ever open a ticket or update the documentation?
