### ISSUE TITLE
tenant_command does not correctly pass arguments to sub-commands

### ISSUE THREAD

**Issue by suriya** [tomturner/django-tenants#90]
I am using django-tenants version 1.1.7. `tenant_command` does not work as advertised and does not properly pass arguments to sub-commands. The commit 96ced6c4fbfd29e6490d00178798168101ef75eb only fixes part of the problem with the implementation of `tenant_command`.

1) Unable to pass arguments to sub-command. As an example:

```
./manage.py tenant_command shell -s demo --plain
usage: manage.py tenant_command [-h] [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [-s SCHEMA_NAME]
                                command_name [command_name ...]
manage.py tenant_command: error: unrecognized arguments: --plain
```

The `shell` command does have a `--plain` argument.

```
./manage.py shell --plain
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```

2) `tenant_command` does not show its help message

```
$ ./manage.py tenant_command --help
Traceback (most recent call last):
  File ".../lib/python3.5/site-packages/django_tenants/management/commands/tenant_command.py", line 27, in run_from_argv
    app_name = get_commands()[argv[2]]
KeyError: '--help'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File ".../lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File ".../lib/python3.5/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../lib/python3.5/site-packages/django_tenants/management/commands/tenant_command.py", line 29, in run_from_argv
    raise CommandError("Unknown command: %r" % argv[2])
django.core.management.base.CommandError: Unknown command: '--help'
```

**Comment by lorinkoz** [comment]
With the last release, `tenant_command` even stopped passing the schema to the subcommand.
