### ISSUE TITLE
Can't drop public schema on tests

### ISSUE THREAD

**Issue by Lobosque** [tomturner/django-tenants#93]
My tests breaks with any version newer than 1.1.1, here is the stack trace.
Any advise on how to fix this?

```
Traceback (most recent call last):
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
psycopg2.OperationalError: cannot DROP TABLE "auth_permission" because it has pending trigger events


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/django_tenants/test/cases.py", line 44, in tearDown
    self.tenant.delete(force_drop=True)
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/django_tenants/models.py", line 108, in delete
    cursor.execute('DROP SCHEMA %s CASCADE' % self.schema_name)
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/lucas/contentools/backend/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.OperationalError: cannot DROP TABLE "auth_permission" because it has pending trigger events
```

**Comment by bartmika** [comment]
I think I've encountered something similar.

Basically I get something similar when I have this code

```python
    @transaction.atomic
    def tearDown(self):
        users = User.objects.all()
        for user in users.all():
            user.delete()
        super(APICalendarEventWithTenantSchemaTestCase, self).tearDown() # Comment this out
```

But once I commented out that  "super" line of code, the unit test runs successfully.

```python
    @transaction.atomic
    def tearDown(self):
        users = User.objects.all()
        for user in users.all():
            user.delete()
        # super(APICalendarEventWithTenantSchemaTestCase, self).tearDown()
```

**Comment by maxthevoice** [comment]
I added a `ForeignKey('self', ...)` on my CustomUser model and got this error when running a test with tenant_migration activated:

```txt
Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: cannot ALTER TABLE "users_user" because it has pending trigger events


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/project/core_project/tests/test_commands.py", line 39, in test_populate_db_arguments
    f'--super-user-password={super_user_password}',
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/project/core_project/management/commands/populate_db.py", line 52, in handle
    schema_name=schema_name,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/project/organizations/models.py", line 39, in save
    return super().save(verbosity, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_tenants/models.py", line 103, in save
    self.create_schema(check_if_exists=True, verbosity=verbosity)
  File "/usr/local/lib/python3.7/site-packages/django_tenants/models.py", line 194, in create_schema
    verbosity=verbosity)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django_tenants/management/commands/migrate_schemas.py", line 63, in handle
    executor.run_migrations(tenants=tenants)
  File "/usr/local/lib/python3.7/site-packages/django_tenants/migration_executors/standard.py", line 15, in run_migrations
    run_migrations(self.args, self.options, self.codename, schema_name, idx=idx, count=len(tenants))
  File "/usr/local/lib/python3.7/site-packages/django_tenants/migration_executors/base.py", line 36, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 178, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/usr/local/lib/python3.7/site-packages/psqlextra/backend/base.py", line 129, in remove_field
    super(SchemaEditor, self).remove_field(model, field)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 481, in remove_field
    self.execute(self._delete_fk_sql(model, fk_name))
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: cannot ALTER TABLE "users_user" because it has pending trigger events
```

The migration run until there is an existing migration with reference to the CustomUser model. If I mannually remove those fields in the migration file, the test succeed. But it's not the kind of fixe I'm waiting for.

**Comment by kosz85** [comment]
If this is pure migration reason, sometimes it's solved by putting the changes that can't apply in new migration. Maybe there are some actions before that disallow this kind of ALTER later. Check that postgres wants to do smth with current data, as there are pending TRIGGERS. So you need to commit it, and add this changes to tables in new transaction, so new migration is what you seek.

**Comment by maxthevoice** [comment]
Thank you for the quick reply. Then I need to find a way to log the SQL queries during my test to know what is causing the issue and finally, create a new operation in the same new migration'S file to make it work?

**Comment by kosz85** [comment]
You said yourself, that you added `ForeignKey('self', ...) on CustomUser`, so I guess this is where you should check, you also said that when you remove migrations and create them from start it works. So I guess the reason is latest migration. You do not need look at particular SQL's.
If you can, you can as well squash migrations, that would work in similar way as recreating, but this depends on your production DB state.

**Comment by maxthevoice** [comment]
It's not in PROD yet, only on DEV. So this is not a problem to wipe the migrations and recreate them. But I would prefer to know the real cause to know what to do if the same issue happen in PROD later. I searched to know what was that pending trigger and I didn't succeed, so I'll resign and recreate migrations. Thnak you for your time 😺
