### ISSUE TITLE
migrate_schemas is not working after django upgrade to 1.10

### ISSUE THREAD

**Issue by gregabostjancic** [tomturner/django-tenants#96]
You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth.

After django upgrade to 1.10 and django_tenants to 1.1.7 i receive this error. How can i fix this?

thank you

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_tenants/management/commands/migrate_schemas.py", line 47, in handle
    executor.run_migrations(tenants=[self.PUBLIC_SCHEMA_NAME])
  File "/usr/local/lib/python2.7/dist-packages/django_tenants/migration_executors/standard.py", line 11, in run_migrations
    run_migrations(self.args, self.options, self.codename, self.PUBLIC_SCHEMA_NAME)
  File "/usr/local/lib/python2.7/dist-packages/django_tenants/migration_executors/base.py", line 30, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 137, in handle
    run_syncdb = options['run_syncdb'] and executor.loader.unmigrated_apps
KeyError: u'run_syncdb'
```

**Comment by mateuspadua** [comment]
I had a same problem

**Comment by bartmika** [comment]
+1

**Comment by rodolfomartinez** [comment]
+1

**Comment by tomturner** [comment]
Can some please test this in 1.1.8

**Comment by stephdion** [comment]
I have the same problem, i try to test on 1.1.8 but no version

Collecting Django==1.1.8
  Could not find a version that satisfies the requirement Django==1.1.8 (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5)
No matching distribution found for Django==1.1.8

**Comment by stephdion** [comment]
i hope that is ok 1.9  but not working for me...:( same issue

python manage.py migrate_schemas --shared
Unknown command: 'migrate_schemas'
Type 'manage.py help' for usage.

**Comment by stephdion** [comment]
i have test with 1.1.8 
```
Installing collected packages: django-tenants
  Found existing installation: django-tenants 1.2.1
    Uninstalling django-tenants-1.2.1:
      Successfully uninstalled django-tenants-1.2.1
Successfully installed django-tenants-1.1.8
```
and same issue

```
 python manage.py migrate_schemas --shared
Unknown command: 'migrate_schemas

```

**Comment by shazadmaved** [comment]
+1

**Comment by vishnupriyavr** [comment]
For the latest version, the solution will be to add "django_tenants" to the list of installed apps
